### PR TITLE
Remove CART_SRAM_2KB constant (#19)

### PR DESCRIPTION
**Pull request by avivace**
See (#19)

### CODE REVIEW

**Comment by ISSOtm** [comment]
Ah, well, that would be an outright removal, not a deprecation. (OTOH, just moving the constants around doesn't notify the user or anything...)

**Comment by aaaaaa123456789** [comment]
What value do commercial MBC2 carts use?

**Comment by CasualPokePlayer** [comment]
> What value do commercial MBC2 carts use?
0

**Comment by avivace** [comment]
> Ah, well, that would be an outright removal, not a deprecation. (OTOH, just moving the constants around doesn't notify the user or anything...)

Ops, should be better now

**Review by ISSOtm — APPROVED** [review]

**Pull request merged**
